import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function About() {
    return (
        <> 
        <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>About Page</h1>

        <div className={styles.grid}>
        <Link href="/home" className={styles.card}>
        <h2>Go Back</h2>
        </Link>
        </div>
        
        
        
        
        
        
        
       </main>
       </>
    )
}